# This file handles the class selection and assignment towards the output, This file is only designed to be run from the run.py file.


# Random Module Import
import random

# Function to determine random number
def classInt():
    return "The Class is: " + classChosen(random.randint(1, 20))

# Function to determine class chosen based on the number generated by classInt()
def classChosen(ClassNo):
    match ClassNo:
        case 1:
            return "Beastman"
        case 2:
            return "Trapper"
        case 3:
            return "Arcanist"
        case 4:
            return "Gunner"
        case 5:
            return "Stagbreaker"
        case 6:
            return "Artificer"
        case 7:
            return "Barbarian"
        case 8:
            return "Bard"
        case 9:
            return "Cleric"
        case 10:
            return "Druid"
        case 11:
            return "Fighter"
        case 12:
            return "Monk"
        case 13:
            return "Paladin"
        case 14:
            return "Ranger (Revised)"
        case 15:
            return "Rogue"
        case 16:
            return "Sorcerer"
        case 17:
            return "Warlock"
        case 18:
            return "Wizard"
        case 19:
            return "Homebrew Class"
        case 20:
            return "DM's Choice"